<?php $vetKey = array();
$vetKey[0] = array("url" => "acessorios-aparelhos-auditivos", "key" => "Acessórios para aparelhos auditivos", "desc" =>"");
$vetKey[1] = array("url" => "adaptacao-aparelho-auditivo", "key" => "Adaptação de aparelho auditivo", "desc" =>"");
$vetKey[2] = array("url" => "aparelho-auditivo-a-m", "key" => "Aparelho auditivo a m", "desc" =>"");
$vetKey[3] = array("url" => "aparelho-auditivo-a-m-preco", "key" => "Aparelho auditivo a m preço", "desc" =>"");
$vetKey[4] = array("url" => "aparelho-auditivo-argosy", "key" => "Aparelho auditivo argosy", "desc" =>"");
$vetKey[5] = array("url" => "aparelho-auditivo-argosy-preco", "key" => "Aparelho auditivo argosy preço", "desc" =>"");
$vetKey[6] = array("url" => "aparelho-auditivo-argosy-valor", "key" => "Aparelho auditivo argosy valor", "desc" =>"");
$vetKey[7] = array("url" => "aparelho-auditivo-molde", "key" => "Aparelho auditivo com molde", "desc" =>"");
$vetKey[8] = array("url" => "aparelho-auditivo-comprar", "key" => "Aparelho auditivo comprar", "desc" =>"");
$vetKey[9] = array("url" => "aparelho-auditivo-coselgi-preco", "key" => "Aparelho auditivo coselgi preço", "desc" =>"");
$vetKey[10] = array("url" => "aparelho-auditivo-recife-pe", "key" => "Aparelho auditivo em recife pe", "desc" =>"");
$vetKey[11] = array("url" => "aparelho-auditivo-infantil", "key" => "Aparelho auditivo infantil", "desc" =>"");
$vetKey[12] = array("url" => "aparelho-auditivo-infantil-valor", "key" => "Aparelho auditivo infantil valor", "desc" =>"");
$vetKey[13] = array("url" => "aparelho-auditivo-intracanal-invisivel", "key" => "Aparelho auditivo intracanal invisível", "desc" =>"");
$vetKey[14] = array("url" => "aparelho-auditivo-intracanal-preco", "key" => "Aparelho auditivo intracanal preço", "desc" =>"");
$vetKey[15] = array("url" => "aparelho-auditivo-intracanal-valor", "key" => "Aparelho auditivo intracanal valor", "desc" =>"");
$vetKey[16] = array("url" => "aparelho-auditivo-invisivel", "key" => "Aparelho auditivo invisível", "desc" =>"");
$vetKey[17] = array("url" => "aparelho-auditivo-invisivel-preco", "key" => "Aparelho auditivo invisível preço", "desc" =>"");
$vetKey[18] = array("url" => "aparelho-auditivo-invisivel-recarregavel", "key" => "Aparelho auditivo invisível recarregável", "desc" =>"");
$vetKey[19] = array("url" => "aparelho-auditivo-invisivel-valor", "key" => "Aparelho auditivo invisível valor", "desc" =>"");
$vetKey[20] = array("url" => "aparelho-auditivo-melhor-custo-beneficio", "key" => "Aparelho auditivo melhor custo benefício", "desc" =>"");
$vetKey[21] = array("url" => "aparelho-auditivo-melhor-preco", "key" => "Aparelho auditivo melhor preço", "desc" =>"");
$vetKey[22] = array("url" => "aparelho-auditivo-microcanal-preco", "key" => "Aparelho auditivo microcanal preço", "desc" =>"");
$vetKey[23] = array("url" => "aparelho-auditivo-mini-retroauricular", "key" => "Aparelho auditivo mini retroauricular", "desc" =>"");
$vetKey[24] = array("url" => "aparelho-auditivo-nuear", "key" => "Aparelho auditivo nuear", "desc" =>"");
$vetKey[25] = array("url" => "aparelho-auditivo-nuear-valor", "key" => "Aparelho auditivo nuear valor", "desc" =>"");
$vetKey[26] = array("url" => "aparelho-auditivo-onde-comprar", "key" => "Aparelho auditivo onde comprar", "desc" =>"");
$vetKey[27] = array("url" => "aparelho-auditivo-oticon-preco", "key" => "Aparelho auditivo oticon preço", "desc" =>"");
$vetKey[28] = array("url" => "aparelho-auditivo-oticon-valor", "key" => "Aparelho auditivo oticon valor", "desc" =>"");
$vetKey[29] = array("url" => "aparelho-auditivo-idosos", "key" => "Aparelho auditivo para idosos", "desc" =>"");
$vetKey[30] = array("url" => "aparelho-auditivo-idosos-preco", "key" => "Aparelho auditivo para idosos preço", "desc" =>"");
$vetKey[31] = array("url" => "aparelho-auditivo-perda-leve", "key" => "Aparelho auditivo para perda leve", "desc" =>"");
$vetKey[32] = array("url" => "aparelho-auditivo-perda-profunda", "key" => "Aparelho auditivo para perda profunda", "desc" =>"");
$vetKey[33] = array("url" => "aparelho-auditivo-surdez", "key" => "Aparelho auditivo para surdez", "desc" =>"");
$vetKey[34] = array("url" => "aparelho-auditivo-surdez-preco", "key" => "Aparelho auditivo para surdez preço", "desc" =>"");
$vetKey[35] = array("url" => "aparelho-auditivo-zumbido-preco", "key" => "Aparelho auditivo para zumbido preço", "desc" =>"");
$vetKey[36] = array("url" => "aparelho-auditivo-pe", "key" => "Aparelho auditivo pe", "desc" =>"");
$vetKey[37] = array("url" => "aparelho-auditivo-perda-severa", "key" => "Aparelho auditivo perda severa", "desc" =>"");
$vetKey[38] = array("url" => "aparelho-auditivo-pernambuco", "key" => "Aparelho auditivo pernambuco", "desc" =>"");
$vetKey[39] = array("url" => "aparelho-auditivo-preco-recife", "key" => "Aparelho auditivo preço recife", "desc" =>"");
$vetKey[40] = array("url" => "aparelho-auditivo-recarregavel-oticon", "key" => "Aparelho auditivo recarregável oticon", "desc" =>"");
$vetKey[41] = array("url" => "aparelho-auditivo-recarregavel-preco", "key" => "Aparelho auditivo recarregável preço", "desc" =>"");
$vetKey[42] = array("url" => "aparelho-auditivo-receptor-no-canal", "key" => "Aparelho auditivo receptor no canal", "desc" =>"");
$vetKey[43] = array("url" => "aparelho-auditivo-receptor-no-canal-preco", "key" => "Aparelho auditivo receptor no canal preço", "desc" =>"");
$vetKey[44] = array("url" => "aparelho-auditivo-retroauricular", "key" => "Aparelho auditivo retroauricular", "desc" =>"");
$vetKey[45] = array("url" => "aparelho-auditivo-retroauricular-bte", "key" => "Aparelho auditivo retroauricular bte", "desc" =>"");
$vetKey[46] = array("url" => "aparelho-auditivo-retroauricular-preco", "key" => "Aparelho auditivo retroauricular preço", "desc" =>"");
$vetKey[47] = array("url" => "aparelho-auditivo-rexton", "key" => "Aparelho auditivo rexton", "desc" =>"");
$vetKey[48] = array("url" => "aparelho-auditivo-rexton-assistencia-tecnica", "key" => "Aparelho auditivo rexton assistência técnica", "desc" =>"");
$vetKey[49] = array("url" => "aparelho-auditivo-rexton-preco", "key" => "Aparelho auditivo rexton preço", "desc" =>"");
$vetKey[50] = array("url" => "aparelho-auditivo-rexton-recarregavel", "key" => "Aparelho auditivo rexton recarregavel", "desc" =>"");
$vetKey[51] = array("url" => "aparelho-auditivo-rexton-valor", "key" => "Aparelho auditivo rexton valor", "desc" =>"");
$vetKey[52] = array("url" => "aparelho-auditivo-sonic", "key" => "Aparelho auditivo sonic", "desc" =>"");
$vetKey[53] = array("url" => "aparelho-auditivo-sonic-preco", "key" => "Aparelho auditivo sonic preço", "desc" =>"");
$vetKey[54] = array("url" => "aparelho-auditivo-starkey", "key" => "Aparelho auditivo starkey", "desc" =>"");
$vetKey[55] = array("url" => "aparelho-auditivo-starkey-preco", "key" => "Aparelho auditivo starkey preço", "desc" =>"");
$vetKey[56] = array("url" => "aparelho-auditivo-surdez-severa", "key" => "Aparelho auditivo surdez severa", "desc" =>"");
$vetKey[57] = array("url" => "aparelho-auditivo-venda", "key" => "Aparelho auditivo venda", "desc" =>"");
$vetKey[58] = array("url" => "aparelho-zumbido", "key" => "Aparelho para zumbido", "desc" =>"");
$vetKey[59] = array("url" => "aparelho-zumbido-preco", "key" => "Aparelho para zumbido preço", "desc" =>"");
$vetKey[60] = array("url" => "aparelhos-auditivos", "key" => "Aparelhos auditivos", "desc" =>"");
$vetKey[61] = array("url" => "aparelhos-auditivos-baratos", "key" => "Aparelhos auditivos baratos", "desc" =>"");
$vetKey[62] = array("url" => "aparelhos-auditivos-intracanal", "key" => "Aparelhos auditivos intracanal", "desc" =>"");
$vetKey[63] = array("url" => "aparelhos-auditivos-mais-baratos", "key" => "Aparelhos auditivos mais baratos", "desc" =>"");
$vetKey[64] = array("url" => "aparelhos-auditivos-microcanal", "key" => "Aparelhos auditivos microcanal", "desc" =>"");
$vetKey[65] = array("url" => "aparelhos-auditivos-modernos", "key" => "Aparelhos auditivos modernos", "desc" =>"");
$vetKey[66] = array("url" => "aparelhos-auditivos-oticon", "key" => "Aparelhos auditivos oticon", "desc" =>"");
$vetKey[67] = array("url" => "aparelhos-auditivos-zumbido", "key" => "Aparelhos auditivos para zumbido", "desc" =>"");
$vetKey[68] = array("url" => "aparelhos-auditivos-personalizados", "key" => "Aparelhos auditivos personalizados", "desc" =>"");
$vetKey[69] = array("url" => "aparelhos-auditivos-recife", "key" => "Aparelhos auditivos recife", "desc" =>"");
$vetKey[70] = array("url" => "assistencia-aparelho-auditivo", "key" => "Assistencia de aparelho auditivo", "desc" =>"");
$vetKey[71] = array("url" => "assistencia-tecnica-aparelho-auditivo-rexton", "key" => "Assistencia tecnica aparelho auditivo rexton", "desc" =>"");
$vetKey[72] = array("url" => "assistencia-tecnica-aparelho-auditivo-argosy", "key" => "Assistência técnica aparelho auditivo argosy", "desc" =>"");
$vetKey[73] = array("url" => "assistencia-tecnica-aparelho-auditivo-oticon", "key" => "Assistência técnica aparelho auditivo oticon", "desc" =>"");
$vetKey[74] = array("url" => "assistencia-tecnica-aparelho-auditivo-starkey", "key" => "Assistência técnica aparelho auditivo starkey", "desc" =>"");
$vetKey[75] = array("url" => "assistencia-tecnica-aparelho-auditivo", "key" => "Assistência técnica de aparelho auditivo", "desc" =>"");
$vetKey[76] = array("url" => "comprar-aparelho-auditivo", "key" => "Comprar aparelho auditivo", "desc" =>"");
$vetKey[77] = array("url" => "comprar-aparelhos-auditivos-recife", "key" => "Comprar aparelhos auditivos recife", "desc" =>"");
$vetKey[78] = array("url" => "conserto-aparelho-auditivo", "key" => "Conserto de aparelho auditivo", "desc" =>"");
$vetKey[79] = array("url" => "conserto-aparelho-auditivo-recife", "key" => "Conserto de aparelho auditivo em recife", "desc" =>"");
$vetKey[80] = array("url" => "conserto-aparelho-auditivo-oticon", "key" => "Conserto de aparelho auditivo oticon", "desc" =>"");
$vetKey[81] = array("url" => "empresa-aparelho-auditivo", "key" => "Empresa de aparelho auditivo", "desc" =>"");
$vetKey[82] = array("url" => "loja-acessorios-aparelhos-auditivos", "key" => "Loja de acessorios para aparelhos auditivos", "desc" =>"");
$vetKey[83] = array("url" => "lojas-aparelhos-auditivos-recife", "key" => "Lojas de aparelhos auditivos em recife", "desc" =>"");
$vetKey[84] = array("url" => "manutencao-aparelho-auditivo-argosy", "key" => "Manutenção aparelho auditivo argosy", "desc" =>"");
$vetKey[85] = array("url" => "manutencao-aparelho-auditivo-oticon", "key" => "Manutenção aparelho auditivo oticon", "desc" =>"");
$vetKey[86] = array("url" => "manutencao-aparelho-auditivo", "key" => "Manutenção de aparelho auditivo", "desc" =>"");
$vetKey[87] = array("url" => "mapeamento-fala", "key" => "Mapeamento de fala", "desc" =>"");
$vetKey[88] = array("url" => "mapeamento-fala-onde-fazer", "key" => "Mapeamento de fala onde fazer", "desc" =>"");
$vetKey[89] = array("url" => "melhor-aparelho-auditivo-idosos", "key" => "Melhor aparelho auditivo para idosos", "desc" =>"");
$vetKey[90] = array("url" => "melhor-aparelho-auditivo-zumbido", "key" => "Melhor aparelho auditivo para zumbido", "desc" =>"");
$vetKey[91] = array("url" => "neuroestimulacao-auditiva", "key" => "Neuroestimulação auditiva", "desc" =>"");
$vetKey[92] = array("url" => "onde-comprar-aparelho-auditivo-recife", "key" => "Onde comprar aparelho auditivo em recife", "desc" =>"");
$vetKey[93] = array("url" => "onde-comprar-aparelhos-auditivos-baratos", "key" => "Onde comprar aparelhos auditivos baratos", "desc" =>"");
$vetKey[94] = array("url" => "onde-vende-aparelho-auditivo-recife", "key" => "Onde vende aparelho auditivo em recife", "desc" =>"");
$vetKey[95] = array("url" => "pac-processamento-auditivo-central-tratamento", "key" => "Pac processamento auditivo central tratamento", "desc" =>"");
$vetKey[96] = array("url" => "pecas-acessorios-aparelhos-auditivos", "key" => "Peças e acessórios para aparelhos auditivos", "desc" =>"");
$vetKey[97] = array("url" => "preco-aparelho-auditivo", "key" => "Preço de aparelho auditivo", "desc" =>"");
$vetKey[98] = array("url" => "preco-aparelho-auditivo-surdez", "key" => "Preço de aparelho auditivo para surdez", "desc" =>"");
$vetKey[99] = array("url" => "preco-aparelho-auditivo-zumbido", "key" => "Preço de aparelho auditivo para zumbido", "desc" =>"");
$vetKey[100] = array("url" => "reparo-aparelho-auditivo", "key" => "Reparo aparelho auditivo", "desc" =>"");
 ?>